### ISSUE TITLE
Конфликт с модулем Advanced SEO Friendly URLs

### ISSUE THREAD

**Issue by nextonru** [yandex-money/yandex-money-ycms-v2-prestashop#1]
При установке модуля выскакивает ошибка - Не получается установить override: Метод setRequestUri класса Dispatcher 

этот метод уже есть в модуле Advanced SEO Friendly URLs (последняя версия 2.1.1) Prestashop 1.7.2.4

    protected function setRequestUri()
    {
        parent::setRequestUri();
        $remove_enabled = Configuration::get('FSAU_REMOVE_DEFAULT_LANG');
        $current_iso_lang = Tools::getValue('isolang');
        if ($this->use_routes && Language::isMultiLanguageActivated() && !$current_iso_lang && $remove_enabled) {
            $_GET['isolang'] = Language::getIsoById(Configuration::get('PS_LANG_DEFAULT'));
        }
    }

как их можно совместить чтобы оба работали?

**Comment by corsik** [comment]
Только самому разбирать function setRequestUri

**Comment by nextonru** [comment]
Мне посоветовали удалить папку override/classes для устранения конфликта, после этого установить модуль, и модуль заработал

**Comment by corsik** [comment]
Вам дали очень плохой совет, вы удалили все остальные расширения классов которые были туда до этого скопированы другими модулями, в итоге рано или поздно вы наткнетесь на проблемы с работой тех модулей которым так же были необходимы эти расширения!

**Comment by Listware** [comment]
У вас просто конфликт функций. Если обозвать функцию по другому и везде заменить её вызов - нормально отрабатывает

**Comment by corsik** [comment]
@Listware не говорите ерунду. Папка override необходима специально, для расширения или изменения функционала действующий классов и их функций.

**Comment by Listware** [comment]
@corsik, если вы пишете, то читайте пожалуйста написанное. Совет на удаление был не мой, я написал свой коммент про функцию, а у вас какие-то не нормальные подозрения.

**Comment by corsik** [comment]
@Listware читай внимательнее,

**Comment by Zeka13** [comment]
@Listware скорее всего вообще не пользовался этим модулем, тем более на новой Presta
