### ISSUE TITLE
Ошибка после установки

### ISSUE THREAD

**Issue by tritlex** [yandex-money/yandex-money-ycms-v2-prestashop#10]
[PrestaShop] Fatal error in module file /public_html/modules/yandexmodule/lib/exceptions.php:
Cannot redeclare class YandexMoney\Exceptions\APIException

Модуль сырой?

**Comment by ostulov** [comment]
Если у Вас ранее был установлен другой модуль (Y.CMS), то необходимо предварительно удалить файлы модуля Y.CMS, затем устанавливать модуль Y.CMS2.
Мы исправим этот баг в следующих версиях этого модуля.

**Comment by iDdonskoy** [comment]
в версии 1.0.9 после установки при попытке сохранить shopID и ключ выдает [PrestaShop] Fatal error in module file :/modules/yandexmodule/lib/yandex-checkout-sdk/lib/Common/LoggerWrapper.php:
Interface 'Psr\Log\LoggerInterface' not found
старый модуль удален полностью

Так же подозреваю, что формирование успешного платежа без самого платежа так и не убрали, судя по CHANGELOG

**Comment by ostulov** [comment]
Баг был исправлен в версии 1.0.10 .
"формирование успешного платежа без самого платежа" у нас не воспроизводится. Пришлите подробности проблемы на cms@yamoney.ru

**Comment by iDdonskoy** [comment]
Подробно написано уже полгода  в соседнем тикете "ошибочный алгоритм обработки платежа", который отмечен как "bug".

**Comment by ostulov** [comment]
Ошибка при установке была исправлена.
Разбор проблемы с некорректным списанием товара проводим в
https://github.com/yandex-money/yandex-money-ycms-v2-prestashop/issues/4
