### ISSUE TITLE
Модуль выдает ошибки

### ISSUE THREAD

**Issue by MaiklSokolov** [yandex-money/yandex-money-ycms-v2-prestashop#2]
При заходе в администрирование модуля вылетают ошибки:

Unknown error в строке 58 в файле /web/ig/classes/PhpEncryptionLegacyEngine.php
[8192] Function mcrypt_get_iv_size() is deprecated
Unknown error в строке 59 в файле /web/ig/classes/PhpEncryptionLegacyEngine.php
[8192] Function mcrypt_create_iv() is deprecated
Unknown error в строке 60 в файле /web/ig/classes/PhpEncryptionLegacyEngine.php
[8192] Function mcrypt_encrypt() is deprecated

Версия Prestashop: 1.7.2.4
Информация о сервере: CentOS 7 x86_64
Версия веб-сервера: nginx/1.10.2
Версия PHP: 7.1.13
Доступный объем памяти: 128M

На сколько понял причина в увеличении требований к алгоритмам шифрования в php7.1
Пробовал менять MCRYPT_RIJNDAEL_128 на AES-256-CBC - ситуацию не исправляет, возникает куча других ошибок.

Что делаю не так?

**Comment by Listware** [comment]
2 варианта. 
1. Понизить версию PHP.
2. переписать mcrypt_encrypt на openssl_encrypt, изменив немного синтаксис

**Comment by MaiklSokolov** [comment]
Никак не могу понять - чем грозит понижение версии?
Проблемами безопасности в будущем?
Более меленой работой? Использую в этом проекте php-fpm.

Прошу прошения за общий вопрос.

**Comment by Listware** [comment]
Вам лично почти ничем не грозит. Просто если хотите использовать новьё - вам надо под его требования править. Ну или ждать, пока этого не сделают разрабы

**Comment by DaoKakao** [comment]
Странно, почему вообще в модуле идет обращение к PhpEncryptionLegacyEngine.
Это имеет смысл только для PS версии 1.6 и меньше - там используется Rijndael и Blowfish.
При вызове криптовальных функций в 1.7 PhpEncryptionLegacyEngine не нужен.

**Comment by ostulov** [comment]
Исправлено в версии v1.0.11
