### ISSUE TITLE
demoney или test=true

### ISSUE THREAD

**Issue by karopka** [yandex-money/yandex-money-ycms-v2-prestashop#21]
Добрый день,

в модуле не заложена возможность тестирования оплаты? для тестовых магазинов тоже нужно оплачивать реальными деньгами, чтобы проверить работоспособность или где-то можно поменять параметр?

в админке модуля такого параметра не нашёл.

**Comment by ostulov** [comment]
Добрый день!

Для тестирования оплаты необходимо использовать отдельные идентификаторы, которые можно получить  личном кабинете Яндекс.Касы.  В таком случае принимается оплата специальными тестовыми данными  - https://kassa.yandex.ru/docs/guides/#oplata-bankowskoj-kartoj
