### ISSUE TITLE
Ошибка компиляции при создании фида для Маркета

### ISSUE THREAD

**Issue by karopka** [yandex-money/yandex-money-ycms-v2-prestashop#22]
После конфигурации части модуля отвечающей за маркет пытаюсь перейти по ссылке 
example.com/module/yandexmodule/generate 
и получаю ошибку "Compile Error: Cannot use 'Object' as class name as it is reserved"

Такая же ошибка вылетает при сохранении конфигурации если попытаться поменять настройку "Статус товара и способы получения
 Товары в наличии не будут выгружены" на что-то другое

**Comment by ostulov** [comment]
Спасибо за обращение, подготовим исправление для данной ошибки.

**Comment by ostulov** [comment]
Добрый день!

Исправление выложено в версии модуля v1.1.6
