### ISSUE TITLE
Переход на ФФД 1.05

### ISSUE THREAD

**Issue by iDdonskoy** [yandex-money/yandex-money-ycms-v2-prestashop#23]
С 1 января 2019 года вступает в силу новый формат фискальных документов (ФФД 1.05). Добавляются дополнительные параметры:

    признак предмета расчёта (paymentSubjectType);
    признак способа расчёта (paymentMethodType).

Как решить проблему? Месяц до перехода

**Comment by ostulov** [comment]
Добрый день!

Мы планируем выпустить обновление для модуля, которое позволит передавать новые параметры. Следите за обновлениями.

**Comment by ostulov** [comment]
Передача параметров для ФФД 1.05 было добавлено в версии 1.1.2
В настройках модуля можно установить признаки отдельно для доставки и отдельно для товаров.
