### ISSUE TITLE
Логотипы оплат

### ISSUE THREAD

**Issue by LedCloud** [yandex-money/yandex-money-ycms-v2-prestashop#27]
При оплате на яндекс кошелек перепутаны логотипы оплат.
![9](https://user-images.githubusercontent.com/37952504/55722852-77f87f80-5a18-11e9-860f-a63197fc880a.png)

Версия модуля... В престе он указан как 2.0.0, а в шапке настроек 1.1.4

![10](https://user-images.githubusercontent.com/37952504/55722926-ab3b0e80-5a18-11e9-8ce8-35a33938df8d.png)

Prestashop 1.7.5.1

**Comment by ostulov** [comment]
Добрый день!

Спасибо, мы исправим путаницу со способами оплаты.
Приложите, пожалуйста, скриншот страницы, где неправильно отображается номер версии модуля.

**Comment by LedCloud** [comment]
Я не сказал, что он неверный, я написал, что непонятно какой версии модуль.

![11](https://user-images.githubusercontent.com/37952504/55723862-230a3880-5a1b-11e9-8580-ae6c1f6c0fdc.png)
![12](https://user-images.githubusercontent.com/37952504/55723863-23a2cf00-5a1b-11e9-871a-0756f7cac52e.png)

        $this->version         = '1.1.4';
        ...

        $this->displayName      = $this->l('Y.CMS 2.0 Prestashop');

**Comment by LedCloud** [comment]
Ранее у меня был установлен модуль, скачанный по ссылке https://kassa.yandex.ru/manuals/dist/kassa-y.cms-prestashop.zip, он и сейчас там, который в конструкторе имеет следующий код:

$this->name            = 'yandexmodule';
        $this->tab             = 'payments_gateways';
        $this->version         = '1.1.4';
        $this->author          = $this->l('Yandex.Money');
        $this->need_instance   = 1;
        $this->bootstrap       = 1;
        $this->module_key      = 'f51f5c45095c7d4eec9d2266901d793e';
        $this->currencies      = true;
        $this->currencies_mode = 'checkbox';

        $this->bootstrap = true;
        parent::__construct();

        $this->displayName      = $this->l('Y.CMS 2.0 Prestashop');

Возможно поэтому сейчас в списке модулей отображается версия 2.0.0

После обращения в поддрежку яндекса по поводу того, что тот модуль не позволяет отправлять платежи на яндекс кошелек я заменил модуль на расположенный по ссылке https://github.com/yandex-money/yandex-money-ycms-v2-prestashop/archive/master.zip

Который работает и единственная к нему претензия на данный момент - перепутаны картинки логотипов оплат.

**Comment by ostulov** [comment]
"Y.CMS 2.0 Prestashop" - это название модуля, отличающее его от другого модуля, использующегося ранее.

**Comment by ostulov** [comment]
Логотипы способов оплаты исправлены в версии v1.1.8
