### ISSUE TITLE
Страница не найдена при возврате в магазин

### ISSUE THREAD

**Issue by vilerinaru** [yandex-money/yandex-money-ycms-v2-prestashop#28]
Добрый день! При завершении оплаты и нажатии кнопки" возврат в магазин" не выводит спасибо за оплату заказа N, либо,что-то другое... напишите, что добавить в код в модуле и где, чтобы исправить данную проблемму

**Comment by vilerinaru** [comment]
Можно сделать, как в стандартном модуле или вызывать его? 
![20190417_190500](https://user-images.githubusercontent.com/49679316/56303032-bc37fe00-6143-11e9-9c4a-941e322f88c3.jpg)

**Comment by ostulov** [comment]
Добрый день!

Возврат на сайт после оплаты через Яндекс.Кассу ведет на стандартную страницу:
![2019-04-17_19-22-51](https://user-images.githubusercontent.com/37800007/56304208-4aad7f00-6146-11e9-80fb-b0f314aba951.png)

Уточните, что происходит у Вас?

**Comment by vilerinaru** [comment]
Добрый день!
Я делаю платеж через Yandex ДЕНЬГИ, не КАССУ и при возврате в магазин, выходит следующая страница:
![Без-имени-1](https://user-images.githubusercontent.com/49679316/56428385-7a33c700-62bf-11e9-9d79-db33c150d8fa.jpg)

**Comment by vilerinaru** [comment]
Версия prestashop 1.7.5, yandex module 1.1.5. При оплате через yandex деньги логотипы местами поменялись, но сами названия неправильные, где логотип yandex деньги - там оплата картами и наоборот. Установил с нуля prestashop, загружен только один Ваш из сторонних модулей

**Comment by vilerinaru** [comment]
Оплачиваю через модуль yandex деньги (как физическое лицо) - оплата картой

**Comment by ostulov** [comment]
Спасибо за уточнение, исправим.

**Comment by vilerinaru** [comment]
День добрый! Подскажите, пожалуйста, когда планируется модуль с внесенными изменениями?

**Comment by ostulov** [comment]
Добрый день!

Пока точный срок назвать не могу.

**Comment by vilerinaru** [comment]
Добрый вечер! Подскажите, правильная ли ссылка в "RedirectURL" на модуль "callbackwallet" и куда ее надо прописать в notification page? Прошу Вас показать пример на скриншотах. Заранее благодарен.
![Bug](https://user-images.githubusercontent.com/49679316/56909325-571bcb00-6aa8-11e9-8d74-337e656e338a.jpg)

**Comment by vilerinaru** [comment]
На одном из форумов пишут, что должно ссылаться на модуль RedirectWallet?

**Comment by ostulov** [comment]
Адрес из "RedirectURL" необходимо прописать в настройках кошелька, в который будет осуществляться прием оплаты. Ссылка на нужную страницу - https://money.yandex.ru/myservices/online.xml (необходимо будет подтвердить доступ к странице через пароль).

Страница с настройками кошелька выглядит так:
![2019-04-29_19-36-00](https://user-images.githubusercontent.com/37800007/56911674-217dde80-6ab6-11e9-8ab5-3c1ea6d1574a.png)

**Comment by vilerinaru** [comment]
А ссылка на модуль в prestashop у меня правильная?

**Comment by vilerinaru** [comment]
При возврате со страницы оплаты в строке браузера постоянно следующая строка :
мой домен/order-confirmation&id_cart=8&id_module=88&id_order=8&key=1844ac9efb1d6394c80662fb1eee7e63
и надпись: Страница, которую вы ищете, не найдена

**Comment by vilerinaru** [comment]
Заработало!  RedirectURL у Вас идет не на тот модуль - должен идти вместо callbackwallet на RedirectWallet и в этом модуле исправить ошибку, вместо order-confirmation&id_cart, должно быть order-confirmation?id_cart (знак вопроса вместо &) и прописать полные пути к tpl.
![Bug1](https://user-images.githubusercontent.com/49679316/56921952-5f373300-6ac7-11e9-9eb0-25841f160f4a.jpg)

**Comment by vilerinaru** [comment]
Ждем update
