### ISSUE TITLE
не работает Яндекс.Метрика в ycms-v2-prestashop

### ISSUE THREAD

**Issue by Zeka13** [yandex-money/yandex-money-ycms-v2-prestashop#3]
Помогите пожалуйста разобраться с вашим модулем для Prestashop 1.7, не смог добиться от него рабочей Метрики! Ваш модуль точно работает? Какие шаги я могу предпринять, чтобы найти проблему? Заранее спасибо

**Информация:**
Версия модуля 1.0.1
Версия веб-сервера: nginx/1.13.7
Версия PHP: 7.1.1
Версия Prestashop: 1.7.2.4
cURL support: enabled
cURL Information: 7.38.0
Проверял в чистом браузере, расширения/adblock ничего не блокируют (их нет)
В hosts файле никаких адресов для блокировки тоже нет

**Проблема:**
не вижу никаких данных в счётчике, если в адресной строке браузера добавьте к адресу страницы параметр _ym_debug со значением 1, тоже ничего нет

**Comment by Listware** [comment]
Пользовательский откет
Для начала - желательно почитать логи модуля.
Поскольку сам модуль написан для PHP до 7.0, советую понизить версию PHP

**Comment by Zeka13** [comment]
@Listware спасибо за советы, логи, я, разумеется смотрел, ничего интересного там не обнаружил, однако непонятно в какой именно момент их смотреть? Вообще не очень ясно как именно работает этот модуль, код метрики на главную страницу он не добавляет, однако он почему-то есть в админке (в настройке модуля)

ответ PHP на 7 или 5.6 версию никак не помогли

**Comment by Listware** [comment]
В таком случае смотрите в логе сервера.  Все варнинги и эрроры, где упоминается модуль (путь, скрипт, место в скрипте). А если пусто - смотрите в сторону шаблона.

**Comment by Zeka13** [comment]
ещё раз - я смотрел логи сервера, я это уже написал выше
"смотрите в сторону шаблона" - к чему эта вода? Я задавал совершенно другие вопросы.
Модуль НЕ рабочий. Вы хотите сказать что я не прав? На вашей Presta 1.7 всё работает?

**Comment by corsik** [comment]
@Zeka13 мне кажется лучше не мучатся, я уже отказался от идеи его использования, метрику проще поставить сриптом из личного кабинета, а выгрузку в yml я переписывал до рабочего состояния самостоятельно!

**Comment by Listware** [comment]
@Zeka13, мне проще и быстрее создать форк, сделать молча некоторые правки и дать ссылку. Но... поскольку Яндекс извлекает прибыль на своих сервисах, я за них работать не имею желания. В конце концов, деньги зарабатываю не я. Но да, у меня всё работает. Не из коробки, тут я не спорил, я правил сам. Меня интересовали ошибки, а не работает - не работает из коробки. У меня ещё ни одна прошлая версия не работала как мне надо, а не как хочет разработчик, а эта - и подавно. Причём это касается не только Престы. Везде пришлось править.

**Comment by Zeka13** [comment]
@Listware а по-моему ты просто п*****ол, твои комментарии никак не помогают, пожалуйста, не пиши тут, может кто знающий придёт.

@corsik спасибо за совет, понял уже, мёртвый модуль, разработчики не отвечают, на почту тоже. Видимо придётся пользоваться платным из Presta маркета

**Comment by corsik** [comment]
@Zeka13 модуль только вышел, скорей всего они еще будут еще над ним работать, но это не битрикс и даже не opencart, и аудитория у prestashop гораздо меньше. _К сожалению, спасение утопающих дело самих утопающих_

**Comment by DaoKakao** [comment]
Во-первых, надо включить отладочный режим самого престашопа. У PS 1.7 под капотом Symfony и поэтому хрен вы что дельное увидите в логах.

Ну а вообще думаю вряд-ли мы дождёмся нормального "родного" модуля для престы. Потому как модуль этот не в приоритете, не приносит ощутимого трафика/денег, да и сама внутренняя структура компании не шибко способствует.
Так что остаётся энтузиастам взять процесс в свои руки, форкнуть, и развивать самостоятельно.

**Comment by Zeka13** [comment]
Во-первых и в-последних, надо было дождаться фикса вендова, поставил релиз от 30 января, заработало. Хотя есть несколько тупостей в настройки, типо надо сначала сохранить настройку заполненную, потом зайти на форму снова и только тогда нажать на ссылку "Получить токен для доступа к Яндекс.Метрика", а после того как дашь разрешение, тебя редиректит на несуществующую страницу

Тем не менее, теперь, метрика работает, **спасибо**
