### ISSUE TITLE
Конфликт с переопределением другого модуля

### ISSUE THREAD

**Issue by TemKaSD** [yandex-money/yandex-money-ycms-v2-prestashop#41]
Здравствуйте. При включении модуля ошибка: Error!
Действие enable над модулем yandexmodule невозможно. Не получается установить override: Метод setRequestUri класса Dispatcher уже переопределён в модуле fsadvancedurl версии 2.2.0 в 2020-01-15 05:20:10 .

**Comment by ilyandex** [comment]
Добрый день. Напишите пожалуйста на cms@yamoney.ru

**Comment by ostulov** [comment]
Добрый день!

Для решения проблемы Вы можете удалить папку override/classes для устранения конфликта, после этого установить модуль.

Если имеющееся правило Вам необходимо, то для его повторного создания необходим переустановить модуль fsadvancedurl.

**Comment by TemKaSD** [comment]
> Добрый день!
> 
> Для решения проблемы Вы можете удалить папку override/classes для устранения конфликта, после этого установить модуль.
> 
> Если имеющееся правило Вам необходимо, то для его повторного создания необходим переустановить модуль fsadvancedurl.

Отличная рекомендация, снести все переопределения магазина.

**Comment by TemKaSD** [comment]
Для решения конфликта необходимо сделать следующее:

1. Отключаем модули: fsadvancedurl, yandexmodule.
2. Включаем модуль fsadvancedurl.
3. Из файла /override/classes/Dispatcher.php вырезаем метод setRequestUri() и сохраняем его в блокноте.
4. Включаем модуль yandexmodule.
5. Возвращаем на место метод setRequestUri() из fsadvancedurl дополняя данными из метода setRequestUri() yandexmodule.

Должно получится как на скрине.

![Screenshot_1](https://user-images.githubusercontent.com/6318282/74200250-2c56d800-4cb2-11ea-9f1b-63209f9bfb0c.png)
