### ISSUE TITLE
PHP 7.1 + Prestashop 1.6.1.20 + yandex-money-ycms-v2-prestashop 

### ISSUE THREAD

**Issue by Alexey-Tsarev** [yandex-money/yandex-money-ycms-v2-prestashop#45]
According to
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
1.6.1.x works with PHP 7 (7.0 and 7.1 are guaranteed)
but yandex-money-ycms-v2-prestashop after install raised the following error:
> [PrestaShop] Fatal error in module file :.../www/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)

According to
https://github.com/yandex-money/yandex-money-ycms-v2-prestashop/
> PHP 5.4 или выше;

**Please support PHP 7**.

PHP 5.6 is the end of life:
https://www.php.net/supported-versions.php
https://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/

**Comment by ostulov** [comment]
Hello!

Try to install last version of module that was uploaded today - https://github.com/yandex-money/yandex-money-ycms-v2-prestashop/archive/1.1.12.zip

**Comment by Alexey-Tsarev** [comment]
Thanks ostulov,
I tried 1.1.12, but got the same:
[PrestaShop] Fatal error in module file :.../classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)

**Comment by ostulov** [comment]
Alexey,

I suppose, this error is not connected with PHP version. I've tried installation of module version 1.1.12 on PHP 7.1, it worked properly.

**Comment by Alexey-Tsarev** [comment]
The issue is gone.
I updated PS to 1.7.6.4 version.
