### ISSUE TITLE
Ошибки на стадии подтверждения

### ISSUE THREAD

**Issue by truecoders** [yandex-money/yandex-money-ycms-v2-prestashop#5]
Не работает оформление заказа.
После выбора метода оплаты, происходит редирект на сайт Яндекс.Денег.
После подтверждения платежа перекидывает обратно на сайт, где показывается ошибка 404, при этом адрес страницы выглядит так:
`https://site.pro/module/yandexmodule/redirect_wallet?code=669D02417ECFCA8621D6E0DC2ACE5E0F63F1BE1804CC46C91B357FEC61396A046C8B891D53E2586B5ED89AA8E3C1CF6FE4B879E100E163177328B170FE0AE4413B71B4D529E731BBEAF49F48FAE9EB55A753FDF79164E4F1ECFCE1B372884A272C86301C6287FCD26CF59F85BF745AC4C867163EEDD3496`
Контроллера _**redirect_wallet**_ нет, меняем его имя в файле _**/modules/yandexmodule/controllers/fron/tredirectwallet.php**_ на **redirectwallet**
`$this->context->link->getModuleLink('yandexmodule', 'redirectwallet', array(), true),;`
Далее, после подтверждения оплаты, получаем ошибку:
`Syntax error in template "module:yandexmodule/views/templates/front/wallet.tpl" on line 41 "<span id="amount" class="price">{displayPrice price=$total}</span>" unknown tag "displayPrice"`
В файле **_wallet.tpl_** оставляем только `$total`, вместо `displayPrice price=$total`
и получаем следующие ошибки с отсутствием темплейтов.

......
И так далее.
В коде прописаны пути к несуществующим темплейтам, неправильно названы контроллеры и переменные. Модуль абсолютно не работающий.

Теперь несколько вопросов.
1. Вы собираетесь сделать модуль?
2. Яндекс.Деньги заинтересованы в работе своей платежной системы?
3. Зачем это было выкладывать?

Надеюсь вопросы не покажутся риторическими и дело сдвинется с мертвой точки. Это дело репутации вашей организации. Лучше уберите этот "модуль" из доступа, в конце концов, и спокойно скажите, что модуля для Prestashop 1.7 у вас нет.

Версия Prestashop: 1.7.2.5
Текущий шаблон: classic

Информация о сервере: Linux #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
Версия веб-сервера: Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.0.2g
Версия PHP: 7.0.25-0ubuntu0.16.04.1

**Comment by Zeka13** [comment]
@truecoders символично никто не отвечает

**Comment by truecoders** [comment]
> символично никто не отвечает
@Zeka13, я уже свой модуль написал... ответ ждать безтолку, похоже
https://github.com/truecoders/yadpay

**Comment by obattalov** [comment]
Мда.. печально всё это.

**Comment by Zeka13** [comment]
Так и не исправили, хотя обещали в личной переписке, пришлось купить платный модуль и его самому ещё дописывать

**Comment by truecoders** [comment]
Нужно прям в Яндекс написать. Обидно не то, что модуль не делают, а то что выложили заведомо не работающий. Видно денег получили за разработку, а разработать забыли.

**Comment by eightyeight** [comment]
#16
